name: .NET build and test
on: push
jobs:
  continuous-integration:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest]
    steps:
    - name: .NET CI
      uses: brianary/dotnet-ci@695187
      with:
        test-target: Test
