name: PowerShell module deployment
on:
  workflow_run:
    workflows: [".NET build and test"]
    types: [completed]
    branches: [main]
defaults:
  run:
    shell: pwsh
jobs:
  setup:
    name: Setup and confirm module change
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Module update check
      id: is_module_update_test
      run: |
        "is_module_update=$(@(git diff --name-only HEAD~ HEAD -- "$(Resolve-Path .\src\*\*.psd1)").Count -gt 0)" >> $GITHUB_ENV
  publish:
    name: Publish to PowerShell Gallery
    needs: setup
    if: github.env.is_module_update == 'True'
    runs-on: windows-latest
    env:
      gallerykey: ${{ secrets.gallerykey }}
    steps:
    - name: Build
      if: success() && env.gallerykey
      run: dotnet build -c Release
    - name: Publish
      if: success() && env.gallerykey
      run: |
        dotnet publish -c Release
        $MSBuildProjectName = [io.path]::GetFileNameWithoutExtension("$(Resolve-Path ./src/*/*.fsproj)")
        $env:PSModulePath -split ';' |
            ForEach-Object {"$_/$MSBuildProjectName"} |
            Where-Object {Test-Path $_ -Type Container} |
            Remove-Item -Recurse -Force
        Push-Location ./src/*/bin/Release/*/publish
        Import-LocalizedData Module -FileName $MSBuildProjectName -BaseDirectory "$PWD"
        $Version = $Module.ModuleVersion
        $InstallPath = "$env:UserProfile/Documents/PowerShell/Modules/$MSBuildProjectName/$Version"
        if(!(Test-Path $InstallPath -Type Container)) {mkdir $InstallPath}
        Copy-Item * -Destination $InstallPath
        Pop-Location
        Publish-Module -Name $MSBuildProjectName -NuGetApiKey $env:gallerykey
